require: rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false