# fly.toml app configuration file generated for drone-flight-log on 2024-06-16T12:08:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drone-flight-log'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '30s'
    grace_period = '30s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512
