# fly.toml app configuration file generated for drone-flight-log on 2024-06-15T23:37:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drone-flight-log'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
