databases:
  - name: droneflightlog
    databaseName: droneflightlog
    user: shigekni
    region: singapore

services:
  - type: web
    name: droneflightlog
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: droneflightlog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    autoDeploy: false