databases:
  - name: droneflightlog
    databaseName: droneflightlog
    user: DroneFlightLog_backend
    region: singapore

services:
  - type: web
    name: DroneFlightLog_backend
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rake db:migrate && bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: droneflightlog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false